### PR TITLE
Location Photo + Geolocation Recording

### LINKED ISSUE #16: As a player, I want to be able to decline recording geolocation for privacy reasons. (US 08.02.01)
As a player, I want to be able to decline recording geolocation for privacy reasons.

## Acceptance Criteria
- [x] Allow user to toggle between allowing and not allowing geolocation

### LINKED ISSUE #20: As a player, I want to be able to scan QR codes and record a photo of the location or object, and the geolocation of the location or object. (US 02.01.01)
As a player, I want to be able to scan QR codes and record a photo of the location or object, and the geolocation of the location or object.

## Acceptance Criteria
- [x] Must have an activity for scanning codes
- [x] Should prompt user whether to record a photo of the location/object
- [x] Should be able to record photo of location/object
- [x] Should be able to record geolocation

### PR DESCRIPTION
**Pull request by jmmabanta**
### What is new?
- Added feature to take location photo
- Added ability to record location of QR code through device's location
- Added `QRCode(String hash)` constructor so that a QRCode can be initialized just from the QRCode
    - This is primarily for creating QRCode objects from newly-scanned QRCodes
    - @andy-mtng Line 38 on QRCode.java has a TODO where you can put in the visual representation of the code, as well as its generated name and point value
- **REMOVED**: Our own Location class, we can use Android's built-in [Location](https://developer.android.com/reference/android/location/Location) class instead

Should be merged before #3 so when the QRCode is added, it has this information. @FrancesIgwe @IreneRSun Double check this as I feel its important to your work in adding newly-scanned QR codes to a user's profile.

Also, **merge #37 BEFORE this one** as this branch is based off that one.

~~I'll add unit tests for this in a future PR (expect it on Friday/Saturday)~~
nvm, I've added some in this PR 

Closes #16 #20

### CODE REVIEW

**Comment by jmmabanta** [comment]
UI TEST CASES FINALLY PASSED!!!!!
look-at-the-size-of-this-w-spongebob

**Comment by jmmabanta** [comment]
On a BaseFragment, you should now be able to call `getActivePlayer()` to get the Player object thats logged in

**Review by IreneRSun — APPROVED** [review]
lgtm

**Review by FrancesIgwe — APPROVED** [review]
ok! i would have to add testcases for add and remove qr code

**Pull request merged**
