### PR TITLE
Remove upper app name bar from screen

### PR DESCRIPTION
**Pull request by WillQizza**
This bar causes display issues.
Removing it fixes the issues with certain buttons appearing off screen in the UI.

### CODE REVIEW

**Comment by WillQizza** [comment]
Honestly for this PR you probably don't need 2 reviews since it's like 2 lines.

**Comment by jmmabanta** [comment]
Ill run it in just a sec but how the hell does your UI tests pass but when I merged them into master they fail 😕

**Comment by jmmabanta** [comment]
I'll wait for the master github action to work but if the ui test fails, ill need you to comment something out of `.github/workflows/tests.yml` file

**Review by jmmabanta — APPROVED** [review]
lgtm!

**Comment by jmmabanta** [comment]
You can admin merge if you want

**Pull request merged**
