### PR TITLE
updated the comment send method to handle enter key press

### PR DESCRIPTION
**Pull request by FrancesIgwe**

### CODE REVIEW

**Comment by WillQizza** [comment]
Requires ` ./gradlew spotlessApply` to be run for the build to pass
Rerun the tests and it should pass.

**Review by WillQizza — CHANGES_REQUESTED** [review]
Requires  ./gradlew spotlessApply to be run for the build to pass
Rerun the tests and it should pass.

**Review by jmmabanta — APPROVED** [review]

**Comment by FrancesIgwe** [comment]
> Requires ./gradlew spotlessApply to be run for the build to pass Rerun the tests and it should pass.

resolved

**Comment by FrancesIgwe** [comment]
> Requires ./gradlew spotlessApply to be run for the build to pass Rerun the tests and it should pass.
resolved

**Review by WillQizza — APPROVED** [review]

**Pull request merged**
